services:
  zoaholic:
    container_name: zoaholic
    build: .
    restart: always
    ports:
      - 8001:8000
    volumes:
      - ./api.yaml:/home/api.yaml
      - ./data:/home/data
    environment:
      - TZ=Asia/Shanghai
      - DB_TYPE=sqlite
      - DB_PATH=/home/data/stats.db
      # - DATABASE_URL=postgresql://user:pass@host:5432/dbname
      # - CONFIG_URL=http://file_url/api.yaml  # 可选：远程配置
